### ISSUE TITLE
66 errors when building

### ISSUE THREAD

**Issue by jomizrahi92** [AlephNull0/glass-movie-player#3]
I used this app for while now, but now that XE12 came out it broke it, so i am downloading the latest version and now when i build it, i get 66 errors. http://cl.ly/image/3G1P2S3u222C

**Comment by AlephNull0** [comment]
Thanks. This issue was solved by modifying the app to use the GDK. Since the GDK is sanctioned by google, future updates shouldn't break the app anymore.
