### ISSUE TITLE
Broken with XE16

### ISSUE THREAD

**Issue by Reldan71** [AlephNull0/glass-movie-player#5]
Does not work with latest XE16 update.

**Comment by iasandcb** [comment]
For XE 16, I modified a copy from master branch and uploaded https://www.dropbox.com/s/ej1gx040bzz9mwg/Gmp.zip (based on Android Studio) . Please feel free to review and apply the changes.

**Comment by AlephNull0** [comment]
Updated to run with XE17. @iasandcb thanks for the mods. Though I will stay with eclipse for now.

**Comment by iasandcb** [comment]
Nice job. I'd appreciate your work.

**Comment by Reldan71** [comment]
Awesome!  Thanks for your work on this!
